export const actionTypes = {
    SET_CURRENT_ROBOT: 'SET_CURRENT_ROBOT',
    EDIT_SETTINGS: 'EDIT_SETTINGS',
    SET_ROBOTS: 'SET_ROBOTS',
    APPLY_CHANGES: 'APPLY_CHANGES',
    CLOSE_NOTIFICATION: 'CLOSE_NOTIFICATION',
    PUSH_NOTIFICATION: 'PUSH_NOTIFICATION'
};
